package entity;

import java.util.List;

/**
 * A simple implementation of the User interface.
 * Entity that represents a user that is stored in the login API.
 */
public class CommonUser implements User {

    private final String name;
    private final String password;
    private final int currentScore;
    private final int highScore;
    // Note that keys are not the entire question as one line.
    private final List<String> createdQuestionsKeys;

    public CommonUser(String name, String password, int currentScore, int highScore,
                      List<String> createdQuestionsKeys) {
        this.name = name;
        this.password = password;
        this.currentScore = currentScore;
        this.highScore = highScore;
        this.createdQuestionsKeys = createdQuestionsKeys;
    }

    @Override
    public String getName() {
        return name;
    }

    @Override
    public String getPassword() {
        return password;
    }

    @Override
    public int getCurrentScore() {
        return currentScore;
    }

    @Override
    public int getHighScore() {
        return highScore;
    }

    // TODO should we return just the keys or also the questions that were created with said keys? Confused if i even
    //      need to write this getter or if it should only be called by the quiz itself and then randomly choose
    //      questions from the keys.
    // TODO format the output so it doesn't look terrible
    // TODO need to pull previously created question keys from API database that's storing it -> json file
    //      notImplemented yet
    public List<String> getCreatedQuestionsKeys() {
        return this.createdQuestionsKeys;
    }

    /**
     * After a question is created and a key is generated, the respective question key is
     * associated with its creator and appended to their list of created questions.
     * @param key is a unique String, generated by the question creating program.
     *            TODO you can probably reword this better
     *            TODO basically call this when they make a question
     */
    public void addCreatedQuestionsKey(String key) {
        this.createdQuestionsKeys.add(key);
    }
}
