package entity;

import java.util.ArrayList;
import java.util.List;

/**
 * An implementation of the Player interface.
 * Entity that represents a user that is stored in the login API.
 */
public class RegisteredPlayer implements Player {

    private final String username;
    private final String password;
    private final int currentScore;
    private final int highScore;
    // Note that keys are not the entire question as one line.
    private final List<String> createdQuestionsKeys;

    // This is when the player logs in.
    // TODO this needs more implementation based on the login API.
    public RegisteredPlayer(String username, String password) {
        this.username = username;
        this.password = password;
        this.createdQuestionsKeys = new ArrayList<>();
        this.currentScore = 0;
        this.highScore = 0;
    }

    @Override
    public String getUsername() {
        return "Your username is: " + this.username;
    }

    @Override
    public String getPassword() {
        return "Your password is: " + this.password;
    }

    @Override
    public int getCurrentScore() {
        return this.currentScore;
    }

    // TODO need to pull high score from API database that's storing it -> json file notImplemented yet
    @Override
    public int getHighScore() {
        return this.highScore;
    }

    // TODO should we return just the keys or also the questions that were created with said keys? Confused if i even
    //      need to write this getter or if it should only be called by the quiz itself and then randomly choose
    //      questions from the keys.
    // TODO format the output so it doesn't look terrible
    // TODO need to pull previously created question keys from API database that's storing it -> json file
    //      notImplemented yet
    public List<String> getCreatedQuestionsKeys() {
        return this.createdQuestionsKeys;
    }

    /**
     * After a question is created and a key is generated, the respective question key is
     * associated with its creator and appended to their list of created questions.
     * @param key is a unique String, generated by the question creating program.
     *            TODO you can probably reword this better
     *            TODO basically call this when they make a question
     */
    public void addCreatedQuestionsKey(String key) {
        this.createdQuestionsKeys.add(key);
    }
}

